name: zarf
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_search_bar: ^2.1.0
  smooth_star_rating: ^1.1.1
  expandable_text: ^2.2.0
  flutter_swiper: ^1.1.6
  modal_bottom_sheet: ^2.0.0
  searchfield: ^0.5.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
#    - assets/images/public_icon.png
#    - assets/images/cash.png
#    - assets/images/IT.png
#    - assets/images/ENG.png
#    - assets/images/Bus.png
#    - assets/images/school1.png
#    - assets/images/school2.png
#    - assets/images/school3.png
#    - assets/images/school4.png
#    - assets/images/school5.png
#    - assets/images/school6.png
#    - assets/images/zarf_logo.png
#    - assets/images/welcome_01.png
#    - assets/images/welcome_02.png
#    - assets/images/element1.png
#    - assets/images/element2.png
#    - assets/images/element3.png
#    - assets/images/element4.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 400
        - asset: fonts/Inter-Bold.ttf
          weight: 700
    - family: InterSemi
      fonts:
        - asset: fonts/Inter-Bold.ttf



  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
