name: zarf
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.9
  flutter_countdown_timer: ^4.1.0
  open_file: ^3.2.1
  syncfusion_flutter_pdf: ^19.4.50-beta
  flutter_pdfview: ^1.2.1
  file_picker: ^4.3.3
  flutter_screenutil: ^5.0.0+2
  flutter_search_bar: ^2.1.0
  smooth_star_rating: ^1.1.1
  expandable_text: ^2.2.0
  flutter_swiper: ^1.1.6
  modal_bottom_sheet: ^2.0.0
  searchfield: ^0.5.6
  flutter_xlider: ^3.4.0
  provider: ^6.0.1
  shared_preferences: ^2.0.11
  image_picker: ^0.8.4+4
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  localstore: ^1.2.1
  firebase_image: ^1.1.1
  notification_permissions: ^0.6.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.3.4
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.4
  flutter_local_notifications: ^9.2.0
  geolocator: ^8.0.3
  map_launcher: ^2.1.2
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
#    - assets/images/public_icon.png
#    - assets/images/cash.png
#    - assets/images/IT.png
#    - assets/images/ENG.png
#    - assets/images/Bus.png
#    - assets/images/school1.png
#    - assets/images/school2.png
#    - assets/images/school3.png
#    - assets/images/school4.png
#    - assets/images/school5.png
#    - assets/images/school6.png
#    - assets/images/zarf_logo.png
#    - assets/images/welcome_01.png
#    - assets/images/welcome_02.png
#    - assets/images/element1.png
#    - assets/images/element2.png
#    - assets/images/element3.png
#    - assets/images/element4.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 400
        - asset: fonts/Inter-Bold.ttf
          weight: 700
    - family: InterSemi
      fonts:
        - asset: fonts/Inter-Bold.ttf



  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
